# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndb_layout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_search = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_search.sizePolicy().hasHeightForWidth())
        self.comboBox_search.setSizePolicy(sizePolicy)
        self.comboBox_search.setObjectName("comboBox_search")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_search)
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBox_radius = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_radius.setObjectName("checkBox_radius")
        self.horizontalLayout_2.addWidget(self.checkBox_radius)
        self.radioButton_5m = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5m.setObjectName("radioButton_5m")
        self.horizontalLayout_2.addWidget(self.radioButton_5m)
        self.radioButton_10m = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_10m.setObjectName("radioButton_10m")
        self.horizontalLayout_2.addWidget(self.radioButton_10m)
        self.radioButton_25m = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_25m.setObjectName("radioButton_25m")
        self.horizontalLayout_2.addWidget(self.radioButton_25m)
        self.radioButton_custom = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_custom.setObjectName("radioButton_custom")
        self.horizontalLayout_2.addWidget(self.radioButton_custom)
        self.spinBox_radius = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_radius.setObjectName("spinBox_radius")
        self.horizontalLayout_2.addWidget(self.spinBox_radius)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView_search = QtWidgets.QTableView(self.groupBox)
        self.tableView_search.setObjectName("tableView_search")
        self.verticalLayout.addWidget(self.tableView_search)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_import = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_import.sizePolicy().hasHeightForWidth())
        self.pushButton_import.setSizePolicy(sizePolicy)
        self.pushButton_import.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_import.setObjectName("pushButton_import")
        self.horizontalLayout_3.addWidget(self.pushButton_import)
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_search.sizePolicy().hasHeightForWidth())
        self.pushButton_search.setSizePolicy(sizePolicy)
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_3.addWidget(self.pushButton_search)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smooth Operator"))
        self.groupBox.setTitle(_translate("MainWindow", "Operator Search"))
        self.comboBox_search.setItemText(0, _translate("MainWindow", "NACSC ID"))
        self.comboBox_search.setItemText(1, _translate("MainWindow", "Company"))
        self.checkBox_radius.setText(_translate("MainWindow", "Radius Search"))
        self.radioButton_5m.setText(_translate("MainWindow", "5 miles"))
        self.radioButton_10m.setText(_translate("MainWindow", "10 miles"))
        self.radioButton_25m.setText(_translate("MainWindow", "25 miles"))
        self.radioButton_custom.setText(_translate("MainWindow", "Custom"))
        self.pushButton_import.setText(_translate("MainWindow", "Import"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))

